apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: keycloak
  labels:
    service: postgres-data
  name: postgres-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
